apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
    spec:
      containers:
      - name: frontend-cont
        image: vinod3939/vinu:hibye
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: f-service
spec:
  type: NodePort
  selector:
    app: frontend1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30085   # use a different port
